//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebula.Web.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShipmentLocalization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipmentLocalization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nebula.Web.Pages.ShipmentLocalization", typeof(ShipmentLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string not_found_title {
            get {
                return ResourceManager.GetString("not-found.title", resourceCulture);
            }
        }
        
        public static string not_found_button {
            get {
                return ResourceManager.GetString("not-found.button", resourceCulture);
            }
        }
        
        public static string summary_registered {
            get {
                return ResourceManager.GetString("summary.registered", resourceCulture);
            }
        }
        
        public static string summary_received {
            get {
                return ResourceManager.GetString("summary.received", resourceCulture);
            }
        }
        
        public static string summary_sorted {
            get {
                return ResourceManager.GetString("summary.sorted", resourceCulture);
            }
        }
        
        public static string summary_out_for_delivery {
            get {
                return ResourceManager.GetString("summary.out_for_delivery", resourceCulture);
            }
        }
        
        public static string summary_delivered {
            get {
                return ResourceManager.GetString("summary.delivered", resourceCulture);
            }
        }
        
        public static string expected {
            get {
                return ResourceManager.GetString("expected", resourceCulture);
            }
        }
        
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        public static string related_title {
            get {
                return ResourceManager.GetString("related.title", resourceCulture);
            }
        }
        
        public static string delay_text {
            get {
                return ResourceManager.GetString("delay.text", resourceCulture);
            }
        }
        
        public static string delay_button {
            get {
                return ResourceManager.GetString("delay.button", resourceCulture);
            }
        }
        
        public static string letter {
            get {
                return ResourceManager.GetString("letter", resourceCulture);
            }
        }
        
        public static string recipient_title {
            get {
                return ResourceManager.GetString("recipient.title", resourceCulture);
            }
        }
        
        public static string sender_title {
            get {
                return ResourceManager.GetString("sender.title", resourceCulture);
            }
        }
        
        public static string details_title {
            get {
                return ResourceManager.GetString("details.title", resourceCulture);
            }
        }
        
        public static string events_title {
            get {
                return ResourceManager.GetString("events.title", resourceCulture);
            }
        }
        
        public static string events_empty {
            get {
                return ResourceManager.GetString("events.empty", resourceCulture);
            }
        }
        
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        public static string updated {
            get {
                return ResourceManager.GetString("updated", resourceCulture);
            }
        }
    }
}
