//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebula.Web.Pages.Auth {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegisterLocalization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterLocalization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nebula.Web.Pages.Auth.RegisterLocalization", typeof(RegisterLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        public static string fields_email {
            get {
                return ResourceManager.GetString("fields.email", resourceCulture);
            }
        }
        
        public static string fields_password {
            get {
                return ResourceManager.GetString("fields.password", resourceCulture);
            }
        }
        
        public static string fields_password_confirmation {
            get {
                return ResourceManager.GetString("fields.password-confirmation", resourceCulture);
            }
        }
        
        public static string sign_in {
            get {
                return ResourceManager.GetString("sign-in", resourceCulture);
            }
        }
    }
}
