//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebula.Web.Pages.Account {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShipmentsLocalization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipmentsLocalization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nebula.Web.Pages.Account.ShipmentsLocalization", typeof(ShipmentsLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        public static string sender_default {
            get {
                return ResourceManager.GetString("sender.default", resourceCulture);
            }
        }
        
        public static string arrived {
            get {
                return ResourceManager.GetString("arrived", resourceCulture);
            }
        }
        
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        public static string empty_title {
            get {
                return ResourceManager.GetString("empty.title", resourceCulture);
            }
        }
        
        public static string empty_button {
            get {
                return ResourceManager.GetString("empty.button", resourceCulture);
            }
        }
    }
}
