//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebula.Web.Layout {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainLayoutLocalization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLayoutLocalization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nebula.Web.Layout.MainLayoutLocalization", typeof(MainLayoutLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string logo_aria {
            get {
                return ResourceManager.GetString("logo.aria", resourceCulture);
            }
        }
        
        public static string items_search {
            get {
                return ResourceManager.GetString("items.search", resourceCulture);
            }
        }
        
        public static string items_shipments {
            get {
                return ResourceManager.GetString("items.shipments", resourceCulture);
            }
        }
        
        public static string items_account {
            get {
                return ResourceManager.GetString("items.account", resourceCulture);
            }
        }
        
        public static string items_sign_out {
            get {
                return ResourceManager.GetString("items.sign-out", resourceCulture);
            }
        }
        
        public static string items_sign_in {
            get {
                return ResourceManager.GetString("items.sign-in", resourceCulture);
            }
        }
        
        public static string items_sign_up {
            get {
                return ResourceManager.GetString("items.sign-up", resourceCulture);
            }
        }
    }
}
