name: Publish Docker image

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to NuGet registry
        run: dotnet nuget update source github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
      - name: Publish
        run: |
          dotnet publish Nebula --os linux --arch x64 \
          -c Release \
          -p:Version="${{ github.ref_name }}" \
          -p:PackageProjectUrl="${{ github.server_url }}/${{ github.actor }}/${{ github.repository }}" \
          -p:ContinuousIntegrationBuild=true \
          -p:ContainerRegistry="ghcr.io" \
          -p:ContainerRepository="${{ github.repository }}" \
          -p:ContainerImageTags="\"${{ github.ref_name }};latest\"" \
          -p:ContainerBaseImage="mcr.microsoft.com/dotnet/aspnet:10.0.0-preview.5" \
          /t:PublishContainer
